const StreamsTypes = {
  CREATE_STREAM: "CREATE_STREAM",
  FETCH_STREAM: "FETCH_STREAM",
  FETCH_STREAMS: "FETCH_STREAMS",
  UPDATE_STREAM: "UPDATE_STREAM",
  DELETE_STREAM: "DELETE_STREAM"
}

export default StreamsTypes;